sudo: required
services:
  - docker

before_install:
  - docker build -t dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerreact npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "ap-south-1"
  app: "helloworld"
  env: "Helloworld-env"
  bucket_name: "elasticbeanstalk-ap-south-1-618548706388"
  bucket_path: "reactdocker"

  on:
    branch: master
