sudo: required
services:
  - docker

before_install:
  - docker build -t dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerreact npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "ap-south-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-618548706388"
  bucket_path: "react-docker"

  on:
    branch: master
